### ISSUE TITLE
Error Messages with English Translation

### ISSUE THREAD

**Issue by KyleCo76** [OGSteam/ogspy#103]
I have error messages pop up on my installation of OGSpy. I am using the English translations when these messages appear. I have attached screenshots of the pages that the messages appear in:

Administration Page
![OGSpyAdmin](https://user-images.githubusercontent.com/2716352/55703528-78a0ff80-599f-11e9-955c-bfffc6f96de5.png)

Server Parameters Page
![OGSpyParameters](https://user-images.githubusercontent.com/2716352/55704102-016c6b00-59a1-11e9-97b6-15a0ce6222ac.png)

Member Management Page
![OGSpyMemberManagement](https://user-images.githubusercontent.com/2716352/55704051-e6016000-59a0-11e9-8262-f271a641a92a.png)

My Account > Empire
![OGSpyProfile_Empire](https://user-images.githubusercontent.com/2716352/55704161-21039380-59a1-11e9-9aff-5f0afa372c09.png)

My Account > Simulation
![OGSpyProfile_Simulation](https://user-images.githubusercontent.com/2716352/55704199-311b7300-59a1-11e9-92a8-22dbcf9d2c29.png)

Galaxy Page
![OGSpyGalaxy](https://user-images.githubusercontent.com/2716352/55704233-40022580-59a1-11e9-9664-9ccab3056c2b.png)

These kinds of error messages also appear in the mods Xtense and autoupdate

Xtense
![XtenseInfo](https://user-images.githubusercontent.com/2716352/55704274-527c5f00-59a1-11e9-9933-54350bba905d.png)

autoupdate > administration
![AutoUpdateAdmin](https://user-images.githubusercontent.com/2716352/55704300-5d36f400-59a1-11e9-9cf0-a18ca2b0122d.png)

Thanks for taking the time to look at this.

**Comment by darknoon29** [comment]
Fixed with Release 3.3.7
