### ISSUE TITLE
Connexion impossible v3.3.4 - FTP FREE

### ISSUE THREAD

**Issue by Wayres** [OGSteam/ogspy#108]
Bonjour,
​
​j'ai réalisé l'installation de OGSPY 3.3.4 sur un serveur FTP FREE, et je rencontre un problème pour me connecter "Les données transmises sont incorrectes".
​
​J'ai fais plusieurs essaies : 
- remise a zero du ftp free et de bdd
- deploiement du package ogspy 3.3.4
- paramétrage installation (puis suppression repertoire install)
- connexion à ogspy : erreur - Les données transmises sont incorrectes

- Nouvelle remise à remise a zero du ftp
- installation ogspy v3.3.0
- connexion ok
- ajout module xtense
- test utilisation xtense (mode debug) -> version ogspy pas assez récente (erreur dans la console du navigateur)

- mise a jour ogspy vers 3.3.4
- connexion à ogspy : erreur - Les données transmises sont incorrectes
​- Xtense : 
​[1555173613218] Xtense : Status: 200 utilities.js:63:5 [1555173613219] Xtense : Response: {"type":"plugin univers","status":0} utilities.js:63:5 [1555173613228] Xtense : setStatus : [undefined ms][OGSpy] La configuration du module Xtense de votre OGSpy ne corresponds pas à votre univers de jeu, merci de vérifier que le lien vers le serveur ogame est correctement renseigné

Merci d'avance pour votre aide
Wayres

**Comment by darknoon29** [comment]
Pour le support, il faudrait plus que tu passes sur notre chan discord. Les pages Free sont un peu spécifiques. Quelle est leur version PHP actuellement ?

**Comment by Roms0406** [comment]
Il a passé beaucoup de temps sur le support avant de poster le bug ici.
Maintenant comme je lui avait dit, on  a eu très souvent des problèmes avec les pages persos Free...

**Comment by darknoon29** [comment]
Oui maintenant Free a fait des maj et certaines choses pourraient fonctionner.

**Comment by darknoon29** [comment]
Pas de news...
