### ISSUE TITLE
@IPv6 non affichée ->2 Warnings

### ISSUE THREAD

**Issue by pitch314** [OGSteam/ogspy#11]
Warning sur page administration :

Apache 2.4.25 / PHP 5.6.30 / OGSpy 3.4.0
URL (IPv6) = http://localhost/ogame/ogspyb/index.php?action=administration&subaction=infoserver

Présence de 2 warnings :
> Warning: array_map() expects parameter 1 to be a valid callback, function 'hexhex' not found or invalid function name in C:\Logiciels\xampp\htdocs\ogspyb\core\functions.php on line 112
Warning: implode(): Invalid arguments passed in C:\Logiciels\xampp\htdocs\ogspyb\core\functions.php on line 112

La fonction concernée est _function decode_ip($int_ip)_ 
(http:// localhost => $int_ip=string(32) "00000000000000000000000000000001")    =>Affichage de "::"
(http://127.0.0.1 => $int_ip=string(8) "7f000001")                              =>Affichage de "127.0.0.1" (pas de warning)

Le problème vient du contexte. (ex dans une classe "foo" il faut faire array_map(array('Foo','myfonction'), ...)
La fonction isolée dans un fichier simple PHP fonctionne correctement.
> <?php
function decode_ip($int_ip)
{
    if (strlen($int_ip) == 32) {
        $int_ip = substr(chunk_split($int_ip, 4, ':'), 0, 39);
        $int_ip = ':' . implode(':', array_map("hexhex", explode(':', $int_ip))) . ':';
        preg_match_all("/(:0)+/", $int_ip, $zeros);
        if (count($zeros[0]) > 0) {
            $match = '';
            foreach ($zeros[0] as $zero)
                if (strlen($zero) > strlen($match))
                    $match = $zero;
            $int_ip = preg_replace('/' . $match . '/', ':', $int_ip, 1);
        }
        return preg_replace('/(^:([^:]))|(([^:]):$)/', '$2$4', $int_ip);
    }
    $hexipbang = explode('.', chunk_split($int_ip, 2, '.'));
    return hexdec($hexipbang[0]) . '.' . hexdec($hexipbang[1]) . '.' . hexdec($hexipbang[2]) . '.' . hexdec($hexipbang[3]);
}
function hexhex($value)
{
    return dechex(hexdec($value));
}

$ip = "00000000000000000000000000000001";
var_dump(decode_ip($ip));

$ip = "7f000001";
var_dump(decode_ip($ip));

**Comment by pitch314** [comment]
J'ai trouvé la solution. Le problème venait bien du contexte et du fait que la fonction est dans un namespace.
Il faut donc faire :
> $int_ip = ':' . implode(':', array_map(__NAMESPACE__.'\hexhex', explode(':', $int_ip))) . ':';

ATTENTION, maintenant que nous utilisons les namespaces, ce problème est identique pour toutes les fonctions à callback ->à vérifier

**Comment by pitch314** [comment]
Zut maudite mise en forme, le bon est :
`$int_ip = ':' . implode(':', array_map(__NAMESPACE__.'\hexhex', explode(':', $int_ip))) . ':';`

**Comment by darknoon29** [comment]
Tu pousseras le code sur le dépôt ? (Tu peux aussi éditer en ligne le fichier de la branche develop)

**Comment by pitch314** [comment]
Je peux mais comme je n'ai pas les droits en écriture, ça serait plus simple que écrive cette ligne.

**Comment by darknoon29** [comment]
Je vois que ton invitation pour le groupe OGSteam est toujours au statut "en attente"

Tu ne l'as pas reçue ?
