### ISSUE TITLE
Ajout params pour install

### ISSUE THREAD

**Issue by pitch314** [OGSteam/ogspy#12]
Ajouter lors de l'installation d'un OGSpy les paramètres de configuration Ogame suivant (comme avec le nombre de galaxie) :
- Vitesses de l'univers [défaut=1]
- Dépôt de ravitaillement (présence O/N) [défaut=O]

**Comment by darknoon29** [comment]
Dépôt de ravitaillement on peut même supprimer l'option je penses. C'est désormais présent sur tous les univers de jeu.

**Comment by pitch314** [comment]
Je pense aussi que l'option n'a plus lieu d'être
