### ISSUE TITLE
Vue Galaxie : Affichage RE Multiples

### ISSUE THREAD

**Issue by machine62** [OGSteam/ogspy#120]
Reconstitution des RE dans la vue galaxie, choix de l'affichage des RE

=> reconstitution d'un seul RE ( comme actuellement) 
ou 
=> affichage des differents RE ( à la suite ou liste deroulant /...)

**Comment by darknoon29** [comment]
Il est possible que je regarde cette partie plus tôt vu que j'ai un fix à faire sur la 3.3.5 dans la zone ☺️

**Comment by Roms0406** [comment]
Je donne mon avis au passage (merci machine d'avoir fait l'effort à ma place ^^)

Il es dommage de se priver de la visualisation des anciens RE, en effet ils sont sotockés mais non affichables, et dans le cas d'un raideur qui veut faire un suivi de cible (ce à quoi servent les RE en grande partie) l'historique des RE est un plus non négligeable ;)

**Comment by machine62** [comment]
Je le pense aussi Roms.
Plusieurs options s'offrent on peut concaténer le premier avec tout ce qu'on a ... Puis lister les re par ordre de date en dessous ou on laisse comme c'est ... :p
