### ISSUE TITLE
Suppression compte utilisateur impossible

### ISSUE THREAD

**Issue by Flowjak** [OGSteam/ogspy#128]
Impossible de supprimer un compte utilsateur , le message d erreur suivant apparait
<img width="1408" alt="Capture d’écran 2019-05-19 à 21 35 38" src="https://user-images.githubusercontent.com/50339107/57987333-4693ba80-7a80-11e9-84e3-8b5b9397ca7f.png">

"C'est lié à un mod qui crée cette table , il faut l integrer a OGSpy au lieu de la creer depuis le mod" Dixit Darknoon

**Comment by darknoon29** [comment]
Table à intégrer à OGSpy. Le fait que ce soit un mod qui l'installe aujourd'hui c'est 🤕

**Comment by darknoon29** [comment]
Corrigé avec c9ac1dd
