### ISSUE TITLE
Limite Nombre de pts Classement atteinte

### ISSUE THREAD

**Issue by darknoon29** [OGSteam/ogspy#14]
Dans mon univers une personne a :
  SUPERMAN (543.066.492) 		26.724.904.853 Pts

Mais dans OGSpy on arrive à la limite max des tables :

1		SUPERMAN			2 147 483 647	Pts

**Comment by machine62** [comment]
du coup passage en BIGINT ? ( le non signé ne reglera pas le pb) ?

**Comment by darknoon29** [comment]
Oui il va falloir ;-)
