### ISSUE TITLE
Lien Forum Alliance : Erreur lorsque l'on saisi un lien Https 

### ISSUE THREAD

**Issue by darknoon29** [OGSteam/ogspy#15]
Message d'erreur sur la transmission de données lorsque l'on saisi un lien https pour le forum d'alliance dans les paramètres d'OGSpy

**Comment by machine62** [comment]
réglé 👍 https://github.com/OGSteam/ogspy/commit/2c02c645e548eb5ade69b6ea9ff87d287bb157e4

**Comment by darknoon29** [comment]
J'avais fait un commit pour ce bug mais je ne l'ai jamais testé :-)

**Comment by machine62** [comment]
j'ai testé le bug avant correction, cela ne marchait pas...

**Comment by darknoon29** [comment]
J'ai bien fait de le laisser ouvert alors :-)
