### ISSUE TITLE
Journal Logs are not Compressed

### ISSUE THREAD

**Issue by darknoon29** [OGSteam/ogspy#153]
Currently archives are not generated for logs and takes more and more space disk.

**Comment by pitch314** [comment]
Les journaux de logs sont soumis au paramètre "Durée de conservation des fichiers logs" qui va de 7j à 365j.
C'est la solution choisie pour réduire l'espace disque. La valeur par défaut est de 7 jours.

Il ne me semble pas utile de compresser si cette maintenance fonctionne correctement, non ?

**Comment by pitch314** [comment]
Vu et confirmé, comportement attendu.

=>Il n'y a pas de compression de log. En revanche, il y a une suppression automatique de ceux-ci périodiquement par rapport à une fenêtre de temps glissante que l'on peut définir de 7j à 1an.
