### ISSUE TITLE
Token refusé par le mod Xtense

### ISSUE THREAD

**Issue by satepestage** [OGSteam/ogspy#159]
Bonjour,

Suite à une bonne discussion avec DarkNoon, je trace ici un problème que j'ai eu.
Version ogspy : 3.3.7-alpha5 (ogspy installé en 3.3.4 (possible) ou à partir d'un git clone (je n'ai plus mon bash_history pour le vérifier).
Version Xtense : 2.7.6
Version Xtense GM : 2.8.3

Suite à un changement de mon pseudo du compte jeu et des coordonnées dans la page profile, Xtense refuse le token.
Un renouvellement de token de change rien.
Par contre, un compte de test envoie bien les données.

Après la recherche de DarkNoon (merci à lui), le champs "ogspy_user.user_password" sur mon 1ier compte n'était pas vide. Le même champs sur le compte de test est bien vide.
Après avoir supprimé le contenu de "ogspy_user.user_password" correspondant à mon 1ier compte, Xtense envoie bien les données.

Bon courage DarkNoon.

**Comment by darknoon29** [comment]
Retesté sur la 3.3.7 et le bug n'est pas reproduit. Difficile de prédire ce qu'il s'est passé...

On devrait être bon sur la release.
