### ISSUE TITLE
Nombre de case des planètes et lunes

### ISSUE THREAD

**Issue by Steffronte** [OGSteam/ogspy#164]
Bonjour,

Le nombre de cases des planètes est bugué dans l'espace personnel : le nombre de case utilisée est incrémenté de 100.

![image](https://user-images.githubusercontent.com/61603453/76647129-786c9500-655c-11ea-9047-b9cab28b9c88.png)

Problème rencontré avec : 
- Google Chrome à jour
- L'extension Xtense à jour
- AGR et Infocompte
- OGSpy 3.3.7
- Xtense 2.7.8

**Comment by darknoon29** [comment]
@Steffronte Je n'ai pas ce soucis. Tu peux essayer sans AGR et Infocompte ?

Si c'est mieux tu les réactive un à un pour savoir le quel provoque ça. Je regarderais pour voir ce qu'on peut faire.
