### ISSUE TITLE
Mise à jour pseudo ig dans le profil

### ISSUE THREAD

**Issue by sboisier** [OGSteam/ogspy#21]
Lorsque l'on utilise un pseudo ig contenant des espaces, il est impossible de mettre ce pseudo dans le profil du joueur.

Ce champ du profil ne prend pas en compte les espaces.

Exemple : Pseudo ig Space Dandy. Si on entre dans le champ pseugo ig du profil de l'utilisateur, on a une erreur lors de la validation.

Par contre, si on met Space%20Dandy le pseudo est enregistré. Je ne sais par contre si le lien xTense <---> OgSpy fonctionne dans ce cas donc si les informations sont bien remontées sur le serveur.

**Comment by machine62** [comment]
réglè

https://github.com/OGSteam/ogspy/commit/6542c576e12490107f5e82c8c9cb59a40994dfd8
