### ISSUE TITLE
Remplacer wz_tooltip.js par une librairie du moment

### ISSUE THREAD

**Issue by darknoon29** [OGSteam/ogspy#25]
Notre librairie est bien trop ancienne et pose des problèmes de qualité.

Les tooltips seraient à revoir avec une nouvelle lib.

**Comment by machine62** [comment]
tu as une idée ?
js / css ?

**Comment by darknoon29** [comment]
Oui c'est cette lib que j'avais essayé mais elle m'avait posé problème au niveau des pop up dans la page galaxie.

**Comment by machine62** [comment]
Ola, c'est une demande pour la 3.3 ou 3.4 ?
3.3 j'imagine ....

**Comment by darknoon29** [comment]
@machine62 C'est à décider en fonction de la complexité. Mais priorité à la 3.4 je penses.

**Comment by juliogonzalez** [comment]
Just in case... Tooltips are not working anymore at recent Firefox (60.6.1es) or Chrome/Chromium (73.0.3683.103)

I tried at the Galaxy and Cartography views and tooltips don't show up.

**Comment by darknoon29** [comment]
Yes, i confirm the issue...

**Comment by machine62** [comment]
Une version plus récente existe :  v. 5.31
Il ne semble pas y avoir d'utilisation de "document.write(htm);"
Reste à voir la compatibilité

V essayer de commencer à alimenter la todo list pour la 3.3.7, je commence à y voir plus clair .. (pour moi ca sera un helper ...

**Comment by machine62** [comment]
derniere mise a jour 
 v5.31   =>  07.11.2008

apres test pas de legende non plus ...

**Comment by machine62** [comment]
A prioriser, on a perdu en fonctionnalité

**Comment by machine62** [comment]
En cours
