### ISSUE TITLE
compatibilité ogame US

### ISSUE THREAD

**Issue by cornalinho** [OGSteam/ogspy#29]
Bonjour,
je reviens vers vous suite à ma demande sur slack de mise en compatibilité avec ogame.us
je suis sous chrome.

la barre xtense du navigateur ne renvoi pas les donnée des rapport d'esponnage realisé et subi.
de plus sur la cartographie, les mod pandore et quimesonde ne marche pas, ils sont vident....

pourriez vous m'aider.

Merci a vous

**Comment by darknoon29** [comment]
Kamino closed and cloned this issue to OGSteam/tool-xtense-web-extension
