### ISSUE TITLE
[maj extern] mettre à jour le JQuery 

### ISSUE THREAD

**Issue by pitch314** [OGSteam/ogspy#294]
Migrer vers le dernier JQuery (3.5.1 ou sup) et vérifier la non régression.

=>https://jquery.com/upgrade-guide/3.5/

**Comment by pitch314** [comment]
La MAJ directe des 2 JS ne fonctionnement pas telle quel et remonte des erreurs JS.

**Comment by darknoon29** [comment]
Très peu utilisé. Update Fait :-) df0c2d80ff242d06b238d69f7cbd635a46a3161b
