### ISSUE TITLE
PHP error log on 3.3.7

### ISSUE THREAD

**Issue by Frespic** [OGSteam/ogspy#301]
Hi guys,

I have this error in the log, but OGSpy 3.3.7 seems to be working fine. 

OVH host
Stable 7.3
PhP engine
Production mode
Application firewall: Enabled 

 Message displayed:
 
 [PHP-ERROR] 8 - Undefined index: spyimport_ogs ; Fichier: /home/danielovgc/ogspy/views/admin_infoserver.php ; Ligne: 119
 
[admin_infoserver.log](https://github.com/OGSteam/ogspy/files/5890434/admin_infoserver.log)

Modifications made: 
1. d08499607a0f2469405465cf29e3aeb9d4b1265f by ddd344fa9f2f875e9b1553b865393b62cf5ea810 in files ogspy/includes/admin_functions.php#L36 and ogspy/mod/autoupdate/core/mod_list.php#L154

2. Change from 24h to 0h in the settings of the autuopdate addon. 

Have fun!

**Comment by pitch314** [comment]
Hi, thank for the report.

Yes this error is know for 3.3.7 and has been pathed in 2526c84214620668d6b9cb0ac97a30d327d02aa1 (dev branch) for the futur 3.3.8.

**Comment by pitch314** [comment]
Normalement, toutes les erreurs PHP d'OGSpy pur (pas les mods) ont été corrigées dans la branche dev (pour la 3.3.8)

Mais on peut utiliser cette issue pour remonter toutes les erreurs PHP, afin d’éviter des oublies.
Il suffit de 2 infos : la page visitée ou URL + le message d'erreur.

For keeping in mind PHP error (should be all done for 3.3.8), we can use this thread for all other PHP error log in relation on OGSPy core.
Post with just :
 - visited page or URL
 - PHP error log message


For all other PHP error ( file ogpsy/mod/...) should be post on the github of the mentioned mod.

**Comment by darknoon29** [comment]
Corrigé
