### ISSUE TITLE
Erreur de calcul de production

### ISSUE THREAD

**Issue by Th3-Dct0r** [OGSteam/ogspy#312]
**Décrire le problème**
La production de ressources est négative ainsi que le ratio
![image](https://github.com/OGSteam/ogspy/assets/133211480/6487647c-a761-4051-848e-b49948f3c07c)

Dans le menu "Espace personnel"
![image](https://github.com/OGSteam/ogspy/assets/133211480/a687676e-2093-44b6-8660-6f504fccb6de)

Dans ogame, la prod est bien positive et sans manque d'énergie :
![image](https://github.com/OGSteam/ogspy/assets/133211480/b30a75c5-d6ee-4b8d-a9df-695807c31168)

**Versions:**
 - OGSpy: 3.3.8
 - Xtense 2.9.10
 - PHP 8.2

**Comment by machine62** [comment]
https://github.com/OGSteam/ogspy/commit/36222f7fa69924adba394dae80c0544f2e25468d
