### ISSUE TITLE
[token] salt

### ISSUE THREAD

**Issue by machine62** [OGSteam/ogspy#38]
génération d'un  salt [ durant installation ]

**Comment by darknoon29** [comment]
Hello, En ce qui concerne le salt j'ai fait une modif pour le créer à la première utilisation de la classe.

A voir si c'est suffisant ;-)

**Comment by machine62** [comment]
oki super ... 

je ne sais pas ce que j'ai fait .... :s

**Comment by machine62** [comment]
sur une installation  neuve c'est oki ....
