### ISSUE TITLE
Comptage des Boosters dans l'espace personnel incorrect

### ISSUE THREAD

**Issue by darknoon29** [OGSteam/ogspy#39]
Remontée Forum
> 
> J'ai trouvé un petit bug sur le nombre des cases dans l'espace personnel, les boosters cases sont comptés 2 fois, au lieu d'avoir un +15 sur planète ou un +6 sur lune j'ai +30 et +6.
> Mais seulement dans la page empire, dans la page simulation, les cases des planètes sont correctes.

**Comment by machine62** [comment]
Ola,
je ne confirme pas le bug dans mon espace perso ...
j'ai un +15 ingame et un +15 dans mon espace perso 

Mais seulement dans la page empire, => ca c'est curieux par contre

**Comment by darknoon29** [comment]
@Choubakawa Tu as un screenshot ?

**Comment by Choubakawa** [comment]
La différence sur les lunes:
![Lune IG](https://i62.servimg.com/u/f62/17/34/57/25/captur11.jpg)
![Lune OGSPY](https://i62.servimg.com/u/f62/17/34/57/25/captur11.png)

La différence sur les planètes:
![Planète IG](https://i62.servimg.com/u/f62/17/34/57/25/captur13.png)
![Planète OGSPY](https://i62.servimg.com/u/f62/17/34/57/25/captur12.png)

Et l'onglet simulation qui est correct
![Simulation](https://i62.servimg.com/u/f62/17/34/57/25/simula10.png)

**Comment by darknoon29** [comment]
Je vois déjà un bug dans Xtense dans la récupération des boosters. C'est toujours le même qui est remonté.

**Comment by darknoon29** [comment]
Je ne penses pas que tu avais plusieurs boosters d'activés mais ce bug devrait t’intéresser aussi : https://github.com/OGSteam/tool-xtense-web-extension/issues/23

**Comment by darknoon29** [comment]
@Choubakawa J'ai revu le code et c'est lié à ce qui est enregistré en base de données. Je ne sais plus où tu es hébergé mais si tu es sur OGSpy.fr je peux regarder directement

**Comment by Choubakawa** [comment]
On est sur OGSpy.fr

**Comment by darknoon29** [comment]
@Choubakawa C'est un choix du développeur en fait : tu penses que le nombre utilisé/ total devrait inclure l'extension ou être séparé ?
En fonction de la réponse j'appliquerais l'idée aux 2 pages (Empire et SImulation)

**Comment by Choubakawa** [comment]
Inclut, comme ce qu'on voit sur Ogame, mais avoir l'information du nombre que donne de l'extension est bien (comme en ce moment)

**Comment by darknoon29** [comment]
Ça marche je fais ça 😉

**Comment by darknoon29** [comment]
Correctif inclus dans la prochaine version
