### ISSUE TITLE
Adminstration : Nombre de Galaxies ou de systèmes ne devrait pas pouvoir être vide

### ISSUE THREAD

**Issue by darknoon29** [OGSteam/ogspy#397]
**Décrire le problème**
Lorsque l'une des deux éléments est vide cela peut conduire à beaucoup d'erreur notament dans galaxy_statistics()

**Etapes nécessaires pour reproduire le problème**
![image](https://github.com/OGSteam/ogspy/assets/13015521/f20718c6-a1c7-4f41-8564-1cbe70d15716)

![image](https://github.com/OGSteam/ogspy/assets/13015521/92abaa18-e524-4b22-90fe-28a784937282)

**Résultat Attendu**
Toujours avoir une veleur ou remonter une erreur

**Capture d'écrans**
Une capture d'écran nous permet d'être sûr du problème rencontré et de vérifier que tout va bien après le correctif.

**Versions:**
 - OGSpy: 3.3.8

**Autres informations utiles**
tout ce que vous pouvez ajouter et qui nous serait utile pour traiter le Bug

**Comment by machine62** [comment]
Beau retour de bug.
