### ISSUE TITLE
PHP 7.0 Requis

### ISSUE THREAD

**Issue by darknoon29** [OGSteam/ogspy#44]
PHP 5.6 will be required for this release.

https://secure.php.net/supported-versions.php

**Comment by machine62** [comment]
check à implémenter dans la monté en version

**Comment by machine62** [comment]
question, on averti ? ou on bloque tout ?

as tu un retour des version php utilisées sur ton site de statistique ?

**Comment by darknoon29** [comment]
On averti car je penses qu'on sera fonctionnel quand même sur du 7.0

**Comment by darknoon29** [comment]
Après c'est une question de sécurité côté php
