### ISSUE TITLE
Chiffrement des mots de passes

### ISSUE THREAD

**Issue by darknoon29** [OGSteam/ogspy#46]
Prévoir une transition vers un chiffrement de mots de passes plus sécurisé. Une version intermédiaire sera nécessaire pour la conversion des mots de passes au moment du Login de l'utilisateur.

Pour les autres ce sera un Reset par email.

**Comment by darknoon29** [comment]
Reste à gérer la connexion xtense désormais ;-)

**Comment by Itori** [comment]
Une idée de comment tu veux faire ça ? 
-  Transformation du mdp avant envoi à ogspy  pour éviter le stockage en clair ?
- Envoi en clair via http ? (On est déjà comme ça je crois)
- Autre ?
