### ISSUE TITLE
Affichage message erreur  espace personnelle ( Empire ) 

### ISSUE THREAD

**Issue by Pascal-Linssen** [OGSteam/ogspy#49]
Message dans espace personnelle dans la vue empire quand le niveau de log PHP à ERROR est activer 

Notice: Undefined offset: 102 in /public_html/ogspy/views/home_empire.php on line 348

![image](https://user-images.githubusercontent.com/5812429/43599062-a35134c0-9686-11e8-81c3-9b1c85c3526b.png)

**Comment by machine62** [comment]
je n'arrive pas a reproduire le bug

**Comment by darknoon29** [comment]
Tu le vois quand tu n'as aucune planète en bdd

**Comment by darknoon29** [comment]
Mais je crois l'avoir déjà corrigé quelque part (3.4 ou 3.3)

**Comment by machine62** [comment]
justement, j'ai pris soin de supprimer mes planètes (sauf une ), pour être dans les mêmes conditions que sur la capture
test sur serveur en prod et serveur de dev ...

la correction doit vraisemblablement etre sur la 3.3

**Comment by darknoon29** [comment]
Cool du coup on peut fermer celui là
