### ISSUE TITLE
bug update mod

### ISSUE THREAD

**Issue by machine62** [OGSteam/ogspy#57]
cf :  https://github.com/OGSteam/mod-autoupdate/issues/21

Lors de la mise à jour du mod Inactifs de l'ancienne version 1.0.8 vers la nouvelle 1.0.10
La mise à jour se déroule correctement mais au retour sur le tableau de mise à jour la version installée reste en 1.0.8 et propose de maj vers 1.0.10

En désinstallant le mod et en le réinstallant directement, la bonne version (1.0.10) est bien prise en compte

**Comment by darknoon29** [comment]
Pas de contrainte au niveau de la fonction d'install du mod. Seraitce le champ en BDD qui serait trop juste ? 

Un varchar de 10 mais si on insère de l'utf8 les points peuvent compter double

**Comment by darknoon29** [comment]
A essayer : version VARCHAR(10) CHARACTER SET utf8,

**Comment by machine62** [comment]
va pour passage en varchar(10) 
https://github.com/OGSteam/ogspy/commit/6e2603cacd2d421657883dac94ecc6c96febaad2
