### ISSUE TITLE
Ajout ID

### ISSUE THREAD

**Issue by machine62** [OGSteam/ogspy#58]
Modification du schema BDD
Ajout des ID joueur et alliance 
dans galaxie + classements

**Comment by darknoon29** [comment]
Nomme les player_id si possible. Séparons ce qui est jeu de l'outil

**Comment by machine62** [comment]
ok, va pour 
player_id et ally_id

**Comment by darknoon29** [comment]
Petite tache à faire côté xtense alors pour remonter tout ça

**Comment by machine62** [comment]
et superapix ...  :p
ca sera après mise à jour  ...

**Comment by machine62** [comment]
par ailleurs puisque le sujet va etre evoqué, je vais ajouter table player et table ally, on va bien finir par lier les id au joueurs/alliance ^^

**Comment by machine62** [comment]
https://github.com/OGSteam/ogspy/commit/c069e11b73f052dba507cc21ab325127a91200b2
https://github.com/OGSteam/ogspy/commit/397e0e870b1a752695562f6e64c11ae8b69a0a94
https://github.com/OGSteam/ogspy/commit/19b42d42c55633e2fdf0d6f91096f45b4b1199e4
