### ISSUE TITLE
Bug des defenses de la planete sur la lune

### ISSUE THREAD

**Issue by mascotte88** [OGSteam/ogspy#6]
Lorsqu'il y a pas de defense sur une lune (a vérifier) les defenses de la planete remonte sur la lune et nous avons les defenses en double, cela peut s'averer etre trompeur lorsque l'on recherche une info

**Comment by machine62** [comment]
Bug encore d'actualité ?

**Comment by Roms0406** [comment]
Chez lui oui
Si spy planète et lune, il se retrouve avec les défenses planétaires sur le RE de la lune
Je n'ai pas réussi à reproduire le bug perso

**Comment by machine62** [comment]
A mon sens, ca semble plus tourner vers Xtense ....

**Comment by Roms0406** [comment]
Aucune idée pour le coup :(

**Comment by pitch314** [comment]
@mascotte88, ce bug est toujours d'actualité ??
