### ISSUE TITLE
Mise à jour de 3.3.2 vers 3.4

### ISSUE THREAD

**Issue by Fouine91** [OGSteam/ogspy#7]
Bonjour,

J'ai voulu mettre à jour OGSpy en 3.4, j'ai donc sauvegardé fichiers et base de données. Ensuite j'ai uploadé le contenu du zip obtenu sur github en écrasant les fichiers existants.
Lorsque je veux lancer l'install pour mettre à jour, j'obtiens une page blanche et dans les logs du serveur web j'ai ceci :
PHP Parse error:  syntax error, unexpected '[' in /home/vhosts/ogam/ogspy/vendor/sabre/uri/lib/functions.php on line 45
Apache version 2.2.15
PHP version 5.3.3

Merci d'avance.
Cdt, Thibaut.

**Comment by darknoon29** [comment]
Pour cette librairie il est demandé PHP 5.4.7.
Je vais voir si on l'utilise encore et si elle doit être conservée ou pas.

**Comment by Fouine91** [comment]
Bonjour,
Merci de la réponse, je me doutais gros comme une maison que ma version de PHP était trop ancienne ! Et malheureusement mes précédentes tentatives de mise à jour php53 vers php54 se sont soldées par un échec, mes sites ne fonctionnaient plus du tout.
Je croise les doigts.
Merci.
Cdt, Thibaut.

**Comment by darknoon29** [comment]
Oui et encore PHP 5.4 ne devrait déjà plus être utilisé d'un point de vue sécurité. Il est abandonné depuis Septembre 2015.

Une info intéressante est ici : http://php.net/supported-versions.php

**Comment by Fouine91** [comment]
Bonjour,
J'ai installé une nouvelle machine virtuelle sous Ubuntu 16.04 / Apache 2.4.18 / PHP7, j'ai ensuite dubliqué le dossier ogspy 3.3.2 et sa base de données, cela fonctionne (sauf l'envoi des données par extense, je verrai ça par la suite).
J'ai donc ensuite téléchargé la branche master de OGS 3.4.0 uploadé en ftp le contenu, en écrasant les fichiers existants. Mais lorsque je lance https://monsite/ogspy/install et que je choisi "Mise à jour", le serveur me répond qu'il n'y a pas de mise à jour...
Je peux faire une nouvelle installation de OGSpy 3.4.0, cela fonctionne.
Ais-je merdé sur la procédure ?
Merci.

**Comment by darknoon29** [comment]
Non c'est la bonne procédure pour une version officielle.
Maintenant la version 3.4.0 est encore en développement et le script d'update n'a pas encore été réalisé donc c'est un peu normal si ça ne fonctionne pas  ;-)

Nous travaillerons là dessus lorsque la version sera dans les phases de bete tests.

**Comment by Fouine91** [comment]
Bonjour Anthony,
Ahhhh, pardon, je n'avais pas fait attention que la 3.4.0 était en développement, pardon, je ne t'aurai pas dérangé avec cela. Merci pour tes réponses.
Je vais rester en 3.3.2 car la 3.4.0 sur la base actuelle ne fonctionne pas bien.
Cdt, Thibaut.

**Comment by darknoon29** [comment]
D'acc. N'hésites pas à nous demander si tu as d'autres questions.
