### ISSUE TITLE
structure fichier pour autoloader

### ISSUE THREAD

**Issue by machine62** [OGSteam/ogspy#70]

**Comment by darknoon29** [comment]
Un joli sujet traité avec composer sur la 3.4 :-)

**Comment by darknoon29** [comment]
Oui c'est ça. Tu as les chemins à configurer via composer pour regénérer les liens de l'autoloader. (On avait choisi d'utiliser l'autoloader de composer sur la 3.4)

**Comment by machine62** [comment]
Je sens comme une invitation à faire pareil ....

je v regarder ca
