### ISSUE TITLE
my nickname from the game is not displayed correctly

### ISSUE THREAD

**Issue by TheDaffy27** [OGSteam/ogspy#95]
After logging in, my name is displayed incorrectly
my nickname in the game is X-Men
is the same as my admin nickname -X-Men
http://prntscr.com/mul9yh

**Comment by machine62** [comment]
Hello,
if your nickname is X-men, it isn't a bug.
Ogspy check and log all connection, before your loggin, ogspy log you like "Visiteur non identifié" [unidentified connection]

**Comment by TheDaffy27** [comment]
Is it possible to fix it to display my nickname from the game

**Comment by machine62** [comment]
Improve screen
ne pas voir les "utilisateurs non identifié" si connexion avec même ip en cours
(todo verifier check ip)

**Comment by TheDaffy27** [comment]
http://prntscr.com/mumolx

**Comment by TheDaffy27** [comment]
where and how I can solve this problem
every time I log in to the game, "Visiteur non identifié" is displayed

**Comment by Roms0406** [comment]
It seems like you don't understand.
It is a normal behaviour from the site, each time someone is connecting to the homepage, ogspy will log it.
Then you connect yourself with your own log and it will be logged as well.
As machine62 said before, it will need to improve this screen, by adding an option to not display this type of connection.
For the time being, it is not a bug or a malfunction, it is just the way ogspy works ;)

**Comment by darknoon29** [comment]
Nouveau Bug Créé pour la gestion des sessions
