### ISSUE TITLE
Update vers OGspy 3.3.5 depuis auto update

### ISSUE THREAD

**Issue by mascotte88** [OGSteam/ogspy#98]
Voici l'erreur que j'ai eu lorsque j'ai voulu faire la maj OGspy 3.3.4 vers 3.3.5 depuis l'auto update : 
https://media.discordapp.net/attachments/482651481175097354/559527881152397331/unknown.png?width=881&height=460

**Comment by darknoon29** [comment]
Des espaces non désirés dans les champs : Corrigé avec : 1982505ccb0319f196138614065e3dec86207bbd
