### ISSUE TITLE
Update OGspy 3.3.5 depuis le fichier ftp install

### ISSUE THREAD

**Issue by mascotte88** [OGSteam/ogspy#99]
impossible de faire une mise à jour d'OGspy depuis la 3.3.4 vers la 3.3.5 depuis le fichier install qui se trouve dans le FTP en selectionnant "mise à jour"

ErrNo:1060
Query:
ALTER TABLE `ogspy_user_building` ADD `Dock` SMALLINT(2) NOT NULL DEFAULT '-1' AFTER `Silo`
Error:
Duplicate column name 'Dock'

par contre ma remonté sur le bug depuis le fichier install a prendre avec des pincettes puisque j'avais déjà essayé depuis auto update

en supprimant le dock en double comme dit avant donc au final même soucis via le fichier install  que l'update sur auto update
Query:
ALTER TABLE ogspy_rank_player_points ADD player_id INT(6) NOT NULL DEFAULT '-1' AFTER player
Error:
Incorrect column name 'player_id '

**Comment by darknoon29** [comment]
J'ai vérifié es config et à part faire une installation + un update dans la foulée ça ne devrait pas arriver.

Après c'était un cas possible suite à un soucis de version d'ogspy. Donc je corrige cette mauvaise version dans l'alpha2
